values:
    advanced.auto_power_on: true
    advanced.low_latency_mode: true
    advanced.noise_cancellation: true
    advanced.three_call_enable: true
    basic.ic_model: 1
    basic.low_power_warn_time: 600000
    basic.pa_control: false
    basic.vm_operation: erase
    factory.dut_mode_enable: false
    factory.reset_mode: FACTORY_RESET_ALL
    factory.test_mode_timeout: 30
    key_actions.call_scenario.active_click: APP_MSG_NULL
    key_actions.call_scenario.active_double_click: APP_MSG_CALL_ANSWER
    key_actions.call_scenario.active_long: APP_MSG_NULL
    key_actions.call_scenario.incoming_click: APP_MSG_NULL
    key_actions.call_scenario.incoming_double_click: APP_MSG_CALL_ANSWER
    key_actions.call_scenario.incoming_long: APP_MSG_CALL_HANGUP
    key_actions.call_scenario.incoming_triple_click: APP_MSG_NULL
    key_actions.call_scenario.outgoing_click: APP_MSG_NULL
    key_actions.call_scenario.siri_click: APP_MSG_NULL
    key_actions.call_scenario.siri_double_click: APP_MSG_NULL
    key_actions.music_scenario.tws_connected_phone_connected_click_l: APP_MSG_VOL_DOWN
    key_actions.music_scenario.tws_connected_phone_connected_click_r: APP_MSG_VOL_UP
    key_actions.music_scenario.tws_connected_phone_connected_double_click_l: APP_MSG_MUSIC_PP
    key_actions.music_scenario.tws_connected_phone_connected_double_click_r: APP_MSG_MUSIC_PP
    key_actions.music_scenario.tws_connected_phone_connected_long_l: APP_MSG_OPEN_SIRI
    key_actions.music_scenario.tws_connected_phone_connected_long_r: APP_MSG_OPEN_SIRI
    key_actions.music_scenario.tws_connected_phone_connected_triple_click_l: APP_MSG_MUSIC_PREV
    key_actions.music_scenario.tws_connected_phone_connected_triple_click_r: APP_MSG_MUSIC_NEXT
    key_actions.music_scenario.tws_disconnected_phone_connected_click_l: APP_MSG_VOL_DOWN
    key_actions.music_scenario.tws_disconnected_phone_connected_click_r: APP_MSG_VOL_UP
    key_actions.music_scenario.tws_disconnected_phone_connected_double_click_l: APP_MSG_MUSIC_PP
    key_actions.music_scenario.tws_disconnected_phone_connected_double_click_r: APP_MSG_MUSIC_PP
    key_actions.music_scenario.tws_disconnected_phone_connected_long_l: APP_MSG_OPEN_SIRI
    key_actions.music_scenario.tws_disconnected_phone_connected_long_r: APP_MSG_OPEN_SIRI
    key_actions.music_scenario.tws_disconnected_phone_connected_triple_click_l: APP_MSG_MUSIC_PREV
    key_actions.music_scenario.tws_disconnected_phone_connected_triple_click_r: APP_MSG_MUSIC_NEXT
    led_config.call_events.active_call: LED_BLUE_ON
    led_config.call_events.call_end: LED_OFF
    led_config.call_events.incoming_call: LED_BLUE_FAST
    led_config.connection_status.bluetooth_connected: LED_BLUE_ON
    led_config.connection_status.bluetooth_disconnected: LED_RED_SLOW
    led_config.connection_status.pairing_mode: LED_BLUE_FAST
    led_config.connection_status.tws_connected: LED_GREEN_ON
    led_config.connection_status.tws_disconnected: LED_ORANGE_SLOW
    led_config.system_events.charge_complete: LED_GREEN_ON
    led_config.system_events.charging: LED_RED_ON
    led_config.system_events.low_battery: LED_RED_FLASH
    led_config.system_events.power_off: LED_OFF
    led_config.system_events.power_on: LED_BLUE_ON
