schema_version: "1.0"
values:
  # 基础配置分组
  basic.ic_model: 0
  basic.vm_operation: "erase"
  basic.pa_control: true
  basic.low_power_warn_time: 600000
  
  # 按键配置分组
  key_actions.call_scenario.active_click: "APP_MSG_NULL"
  key_actions.call_scenario.active_double_click: "APP_MSG_CALL_ANSWER"
  key_actions.call_scenario.incoming_click: "APP_MSG_NULL"
  key_actions.call_scenario.incoming_long: "APP_MSG_CALL_HANGUP"
  
  key_actions.music_scenario.tws_connected_click_r: "APP_MSG_VOL_UP"
  key_actions.music_scenario.tws_connected_click_l: "APP_MSG_VOL_DOWN"
  key_actions.music_scenario.tws_disconnected_click: "APP_MSG_MUSIC_PP"
  
  # LED配置分组
  led_config.connection_status.bluetooth_connected: "LED_BLUE_ON"
  led_config.connection_status.bluetooth_pairing: "LED_BLUE_FAST"
  led_config.system_events.power_on: "LED_GREEN_ON"
  led_config.system_events.low_battery: "LED_RED_SLOW"
  
  # 工厂设置
  factory.reset_mode: "FACTORY_RESET_MODE_NORMAL"
  factory.auto_power_on: true