values:
  basic.ic_model: 0
  basic.vm_operation: 0
  basic.low_power_warn_time: 600000
  basic.dac_pa_enable: true
  call_actions.active_call.single_click: "APP_MSG_NULL"
  call_actions.active_call.double_click: "APP_MSG_CALL_ANSWER"
  call_actions.active_call.long_press: "APP_MSG_NULL"
  call_actions.incoming_call.single_click: "APP_MSG_NULL"
  call_actions.incoming_call.double_click: "APP_MSG_CALL_ANSWER"
  call_actions.incoming_call.long_press: "APP_MSG_CALL_HANGUP"
  music_actions.tws_connected.right_single_click: "APP_MSG_VOL_UP"
  music_actions.tws_connected.left_single_click: "APP_MSG_VOL_DOWN"
  music_actions.tws_connected.right_double_click: "APP_MSG_MUSIC_PP"
  music_actions.tws_connected.left_double_click: "APP_MSG_MUSIC_PP"
  music_actions.tws_connected.right_long_press: "APP_MSG_OPEN_SIRI"
  music_actions.tws_connected.left_long_press: "APP_MSG_OPEN_SIRI"
  led_config.tws_status.connected: "LED_STA_BLUE_ON"
  led_config.tws_status.disconnected: "LED_STA_RED_ON"
  led_config.bluetooth_status.connected: "LED_STA_ALL_OFF"
  led_config.bluetooth_status.disconnected: "LED_STA_BLUE_FLASH_1TIMES_PER_5S"
  led_config.system_events.power_on: "LED_STA_RED_BLUE_SLOW_FLASH_ALTERNATELY"
  led_config.system_events.power_off: "LED_STA_RED_FLASH_3TIMES"
  led_config.system_events.low_power: "LED_STA_BLUE_FLASH_1TIMES_PER_14S"
  led_config.charging_status.charging: "LED_STA_RED_ON"
  led_config.charging_status.charge_full: "LED_STA_ALL_OFF"
  special_functions.factory_reset.enable_led: true
  special_functions.factory_reset.led_effect: "LED_STA_BLUE_FAST_FLASH_10TIMES"
  special_functions.factory_reset.clear_tws_pairing: false
  special_functions.dut_mode.led_effect: "LED_STA_BLUE_ON"
  advanced.three_way_call: true
  advanced.two_io_led: true
  advanced.factory_reset_timeout: 25
  advanced.soft_poweroff_mode: 2